# Site settings
name: Zaterdag 15-10-22
description: Van 09:00 tot 01:00
url: ""
title: Pretflat FM - Live Visual Radio
keywords: 

stream: "https://stream.pretflatfm.nl/stream"

whatsapp_number: 31613443414
facebook_username: pretflatfm
instagram_username:  pretflatfm
# youtube_username: UCN1R3cUC0jUFpohKSu_Fnow
twitch_username: pretflatfm
twitter_hashtag: PFFM
lastfm_username: pretflatfm
telegram_username: pretflatfm

avatar: yes
avatar_img_path: "imgs/avatar.jpg"

front_img: yes
front_img_path: "imgs/background.jpg"

favicon_img: yes
favicon_img_path: "imgs/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
